export const EPISODE_PLANNER_TIMEOUT_MS = 35000;
export const USER_REQUEST_BRAIN_READY_TIMEOUT_MS = 45000;
export const USER_REQUEST_STILL_PLANNING_AFTER_MS = 9000;
export const CONTINUATION_BRAIN_READY_TIMEOUT_MS = 6000;
